"""empty message

Revision ID: 5b757596191a
Revises: 
Create Date: 2021-04-23 18:53:33.286784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b757596191a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careerpath',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('careerlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skill_careerpath',
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('careerpath_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['careerpath_id'], ['careerpath.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], )
    )
    op.create_table('user_careerpath',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('careerpath_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['careerpath_id'], ['careerpath.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('skill_careerlink',
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('careerlink_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['careerlink_id'], ['careerlink.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_careerlink')
    op.drop_table('user_careerpath')
    op.drop_table('skill_careerpath')
    op.drop_table('careerlink')
    op.drop_table('user')
    op.drop_table('skill')
    op.drop_table('careerpath')
    # ### end Alembic commands ###
